<a href="https://colab.research.google.com/github/rchodavarapuv/MyPersonalFolder/blob/master/Matrix90.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np

def swap(x, y):
  x = x + y
  y = x - y
  x = x - y
  return x, y


a = np.array([[1, 2, 3], [4, 5, 6], [7,8,9]])
a = np.transpose(a)

a[0,:], a[2,:] = swap(a[0,:], a[2,:])

print(a)

[[3 6 9]
 [2 5 8]
 [1 4 7]]
